import Foundation
import SwiftUI

enum JunkCategory: String, CaseIterable, Hashable {
    case userCaches = "User Caches"
    case systemCaches = "System Caches"
    case userLogs = "User Logs"
    case systemLogs = "System Logs"
    case xcodeJunk = "Developer Junk (Xcode)"
    case iosBackups = "iOS Backups"
    case mailDownloads = "Mail Attachments"
    
    var isSafeToDelete: Bool {
        switch self {
        case .userCaches, .systemCaches, .userLogs, .systemLogs, .xcodeJunk:
            return true
        case .iosBackups, .mailDownloads:
            return false // Requires caution
        }
    }
    
    var aiExplanation: String {
        switch self {
        case .userCaches:
            return "These are temporary files created by your apps to load faster (like image caches for Spotify or Chrome). It is completely safe to delete them. Apps will simply recreate the necessary ones the next time you open them."
        case .systemCaches:
            return "Temporary files generated by macOS itself. Deleting these is safe and can sometimes fix weird system glitches, but your Mac might take slightly longer to boot up the very next time while it rebuilds them."
        case .userLogs, .systemLogs:
            return "Log files are just text records of what your Mac and apps have been doing (useful for developers fixing crashes). They serve no purpose for everyday use and are 100% safe to delete."
        case .xcodeJunk:
            return "Xcode 'DerivedData' contains intermediate build results, indexes, and logs from coding projects. If you are not actively compiling a specific app right now, you can safely wipe this. Xcode will just regenerate it next time you build a project."
        case .iosBackups:
            return "These are full backups of your iPhone or iPad made via Finder. Do not delete these unless you are sure you have an iCloud backup or no longer need the local backup data."
        case .mailDownloads:
            return "When you view an attachment in Apple Mail, it saves a hidden copy here. Deleting these frees up space, but means Mail will have to re-download the attachment from the server next time you want to view it."
        }
    }
}

struct JunkItem: Identifiable, Hashable {
    let id = UUID()
    let url: URL
    let category: JunkCategory
    let size: Int64
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func == (lhs: JunkItem, rhs: JunkItem) -> Bool {
        lhs.id == rhs.id
    }
}

@MainActor
class SystemJunkScanner: ObservableObject {
    @Published var junkItems: [JunkItem] = []
    @Published var isScanning = false
    @Published var scanProgress = ""
    @Published var scannedCategories: Set<JunkCategory> = []
    
    var totalJunkSize: Int64 {
        junkItems.reduce(0) { $0 + $1.size }
    }
    
    var safeJunkSize: Int64 {
        junkItems.filter { $0.category.isSafeToDelete }.reduce(0) { $0 + $1.size }
    }
    
    private let fileManager = FileManager.default
    
    func startDeepScan() {
        isScanning = true
        junkItems = []
        scannedCategories = []
        
        Task.detached(priority: .userInitiated) {
            let fileManager = FileManager()
            let home = fileManager.homeDirectoryForCurrentUser
            
            let targets: [(JunkCategory, URL)] = [
                (.userCaches, home.appendingPathComponent("Library/Caches")),
                (.systemCaches, URL(fileURLWithPath: "/Library/Caches")),
                (.userLogs, home.appendingPathComponent("Library/Logs")),
                (.systemLogs, URL(fileURLWithPath: "/Library/Logs")),
                (.systemLogs, URL(fileURLWithPath: "/var/log")),
                (.xcodeJunk, home.appendingPathComponent("Library/Developer/Xcode/DerivedData")),
                (.iosBackups, home.appendingPathComponent("Library/Application Support/MobileSync/Backup")),
                (.mailDownloads, home.appendingPathComponent("Library/Containers/com.apple.mail/Data/Library/Mail Downloads"))
            ]
            
            var results: [JunkItem] = []
            
            for (category, url) in targets {
                await MainActor.run { self.scanProgress = "Scanning \(category.rawValue)..." }
                
                // For performance, we treat top-level folders in these targets as individual items
                // except for specific ones where we might want to list files
                
                if fileManager.fileExists(atPath: url.path) {
                    do {
                        let contents = try fileManager.contentsOfDirectory(at: url, includingPropertiesForKeys: [.isDirectoryKey])
                        
                        for itemUrl in contents {
                            let size = getFolderSize(itemUrl.path, fileManager: fileManager)
                            if size > 0 { // Ignore empty folders
                                let junk = JunkItem(url: itemUrl, category: category, size: size)
                                results.append(junk)
                            }
                        }
                    } catch {
                        // Permissions error or non-existent
                        continue
                    }
                }
                
                let finalResults = results
                await MainActor.run {
                    self.junkItems = finalResults
                    self.scannedCategories.insert(category)
                }
            }
            
            await MainActor.run {
                self.scanProgress = "Scan complete. Found \(self.junkItems.count) items."
                self.isScanning = false
            }
        }
    }
    
    func cleanItem(_ item: JunkItem) async -> Bool {
        do {
            try fileManager.trashItem(at: item.url, resultingItemURL: nil)
            await MainActor.run {
                if let idx = self.junkItems.firstIndex(of: item) {
                    self.junkItems.remove(at: idx)
                }
            }
            return true
        } catch {
            return false
        }
    }
    
    func cleanAllSafeJunk() async {
        let safeItems = junkItems.filter { $0.category.isSafeToDelete }
        for item in safeItems {
            _ = await cleanItem(item)
        }
    }
    
}

private func getFolderSize(_ filePath: String, fileManager: FileManager) -> Int64 {
    do {
        let fileAttributes = try fileManager.attributesOfItem(atPath: filePath)
        if let fileSize = fileAttributes[FileAttributeKey.size] as? NSNumber {
            return fileSize.int64Value
        } else if let type = fileAttributes[FileAttributeKey.type] as? String, type == FileAttributeType.typeDirectory.rawValue {
            var folderSize: Int64 = 0
            if let enumerator = fileManager.enumerator(atPath: filePath) {
                for _ in enumerator {
                    if let attrs = enumerator.fileAttributes {
                        folderSize += (attrs[FileAttributeKey.size] as? NSNumber)?.int64Value ?? 0
                    }
                }
            }
            return folderSize
        }
        return 0
    } catch {
        return 0
    }
}
